import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/master/Footer";
import { Red_Hat_Display } from 'next/font/google';
const makaran = localFont({ src: "./fonts/makaran.woff", variable: "--font-makaran" })

export const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
  variable: '--font-red-hat-display',
});

export const metadata = {
  title: "Mohi Holidays",
  description: "Generated by create next app",
};

import ThemeProvider from "@/components/master/ThemeProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${makaran.variable} ${redHatDisplay.variable}`} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ThemeProvider>
          {children}
          {/* <Footer/> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
